name: Gzillion Artist
favicon: null
layout_spectrum: 0.6375818643718958
typography_spectrum: 0.5621466594748199
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.04850400774739683
  lightness: 0.2589427449274808
  saturation: 0.6543010296300054
  rhythmicContrast: 0.03899962827563286
purpose: []
