title: Gzillion Artist
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 1
favicon: null
name: Gzillion Artist
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.4797639
  saturation: 0.4865093
  rhythmicContrast: 0.5151771
  brandColors:
    - '#101012'
    - '#D2C5B3'
    - '#FDF9ED'
    - '#817261'
    - '#322C26'
typography_spectrum: 0.005902192
