name: Gzillion Artist
favicon: null
layout_spectrum: 1
typography_spectrum: 0.005902192
title: Gzillion Artist
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f11'
    - '#d3c3b3'
    - '#a59586'
    - '#827262'
    - '#4c4439'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
